version: "3.8"

services:
  app:
    image: wu529778790/api.shenzjd.com
    container_name: api.shenzjd.com
    ports:
      - "5252:3000" # 将容器的 3000 端口映射到主机的 3000 端口
    environment:
      - NODE_ENV=production
