import fs from 'fs'
import path from 'path'

const docsDir = path.resolve(process.cwd(), 'docs')

function extractFrontmatter(content) {
  const match = content.match(/^---\s*\n([\s\S]*?)\n---/)
  if (!match) return null
  const lines = match[1].split('\n')
  const fm = {}
  let currentKey = null
  let currentArray = null

  for (const line of lines) {
    if (line.match(/^\s+-\s+(.*)$/)) {
      const val = line.match(/^\s+-\s+(.*)$/)[1].trim()
      if (currentArray && val) currentArray.push(val)
      continue
    }
    const m = line.match(/^(\w[\w-]*):\s*(.*)$/)
    if (m) {
      if (currentKey && currentArray) fm[currentKey] = currentArray
      currentKey = m[1]
      const val = m[2].trim()
      if (val === '' || val === '-') {
        currentArray = []
        fm[currentKey] = currentArray
      } else {
        currentArray = null
        fm[currentKey] = val
      }
    }
  }
  if (currentKey && currentArray) fm[currentKey] = currentArray
  return fm
}

function scanDir(dir) {
  const posts = []
  const entries = fs.readdirSync(dir, { withFileTypes: true })
  for (const entry of entries) {
    if (entry.name.startsWith('.') || entry.name === 'node_modules' || entry.name === '@pages' || entry.name === '_posts') continue
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      posts.push(...scanDir(fullPath))
    } else if (entry.name.endsWith('.md') && entry.name !== 'index.md') {
      const content = fs.readFileSync(fullPath, 'utf-8')
      const fm = extractFrontmatter(content)
      if (fm && fm.title && fm.date) {
        // URL based on file path (stable, title changes don't affect it)
        const url = fullPath
          .replace(docsDir, '')
          .replace(/\.md$/, '.html')
          .replace(/\/index\.html$/, '/')
        // Extract first meaningful paragraph as excerpt
        const body = content.replace(/^---[\s\S]*?---\s*/, '')
        const paragraphs = body
          .split('\n\n')
          .map(p => p
            .replace(/^#+\s+.*$/gm, '') // remove headings
            .replace(/!\[.*?\]\(.*?\)/g, '') // remove images
            .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1') // strip links, keep text
            .replace(/[*_`~]/g, '') // remove markdown formatting
            .replace(/<[^>]+>/g, '') // remove HTML tags
            .trim()
          )
          .filter(p => p.length > 10) // skip very short paragraphs
        const firstPara = paragraphs[0] || ''
        // Extract numeric prefix from filename for sorting
        const numMatch = entry.name.match(/^(\d+)/)
        const order = numMatch ? parseInt(numMatch[1]) : -1

        posts.push({
          title: fm.title,
          date: fm.date,
          url,
          sticky: fm.sticky ? Number(fm.sticky) : 0,
          excerpt: firstPara,
          deprecated: fm.deprecated === 'true' || fm.deprecated === true,
          outdated: fm.outdated === 'true' || fm.outdated === true,
          updated: fm.updated || '',
        })
      }
    }
  }
  return posts
}

const posts = scanDir(docsDir)
posts.sort((a, b) => {
  if (a.sticky && !b.sticky) return -1
  if (!a.sticky && b.sticky) return 1
  // Newest first by date
  return new Date(b.date).getTime() - new Date(a.date).getTime()
})

// Generate TS file with data
const tsContent = `// Auto-generated by scripts/generate-posts.mjs
export interface Post {
  title: string
  date: string
  url: string
  sticky?: number
  excerpt?: string
  deprecated?: boolean
  outdated?: boolean
  updated?: string
}

export const posts: Post[] = ${JSON.stringify(posts, null, 2)}
`

const outPath = path.resolve(process.cwd(), 'docs/.vitepress/theme/data/posts.ts')
const outDir = path.dirname(outPath)
if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true })
}
fs.writeFileSync(outPath, tsContent)
console.log(`[generate-posts] Generated ${posts.length} posts -> posts.data.ts`)
