name: 构建和部署

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 需要获取所有历史记录以创建标签

      - name: 设置Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "19"

      - name: 下载pnpm
        run: npm install -g pnpm

      - name: 安装依赖
        run: pnpm install

      - name: 构建项目
        run: pnpm run build

      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 登录Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Update version and commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          npm version patch -m "chore(release): v%s [skip ci]"

      - name: 获取版本号
        id: version
        run: echo ::set-output name=new-version::$(npm version patch)

      - name: 构建并推送Docker镜像
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: wu529778790/blog.shenzjd.com:${{ outputs.new-version }}

      - name: Push changes
        run: |
          git push
